<?php
$array = str_replace("lii","lij",$array,$i);

$array = str_replace("2","e",$array,$i);
$array = str_replace("3","s",$array,$i);
$array = str_replace("4","c",$array,$i);
$array = str_replace("5","r",$array,$i);
$array = str_replace("6","z",$array,$i);
$array = str_replace("7","y",$array,$i);
$array = str_replace("8","a",$array,$i);
$array = str_replace("9","i",$array,$i);
$array = str_replace("0","e",$array,$i);
$array = str_replace("/","u",$array,$i);

$array = str_replace("honza","jan",$array,$i);
$array = str_replace("jaroslav","jarda",$array,$i);
$array = str_replace("pepa","josef",$array,$i);
$array = str_replace("vasek","vaclav",$array,$i);
$array = str_replace("stanislava","stana",$array,$i);
$array = str_replace("tatana","tatiana",$array,$i);
$array = str_replace("tatiana","tana",$array,$i);
$array = str_replace("bohous","bohumil",$array,$i);
$array = str_replace("bohumir","bohumil",$array,$i);
$array = str_replace("daniela","dana",$array,$i);
$array = str_replace("danuska","dana",$array,$i);
$array = str_replace("daniel","dan",$array,$i);
$array = str_replace("mila","miloslava",$array,$i);
$array = str_replace("mirka","miroslava",$array,$i);
$array = str_replace("mirek","miroslav",$array,$i);
$array = str_replace("ivanka","ivana",$array,$i);
$array = str_replace("iva","ivana",$array,$i);
$array = str_replace("elzbie","elzbiet",$array,$i);
$array = str_replace("eduard","edvard",$array,$i);
$array = str_replace("antonin","ant",$array,$i);
$array = str_replace("fr","frantisek",$array,$i);
$array = str_replace("franta","frantisek",$array,$i);
$array = str_replace("standa","stanislav",$array,$i);
$array = str_replace("vladimir","vlada",$array,$i);
$array = str_replace("vladimira","vladka",$array,$i);
$array = str_replace("jozek","josef",$array,$i);
$array = str_replace("jozef","josef",$array,$i);
$array = str_replace("reinhold","reidhold",$array,$i);
$array = str_replace("jirka","jiri",$array,$i);

?>