<?php
$array = str_replace("cz","z",$array,$i);
$array = str_replace("min","mlin",$array,$i);
$array = str_replace("sza","sta",$array,$i);
$array = str_replace("ngr","nger",$array,$i);
$array = str_replace("eich","ejch",$array,$i);
$array = str_replace("kovsk","ovsk",$array,$i);
$array = str_replace("ndr","nr",$array,$i);
$array = str_replace("chs","sch",$array,$i);
$array = str_replace("ovova","ova",$array,$i);
$array = str_replace("nin","vin",$array,$i);
$array = str_replace("niel","nihel",$array,$i);
$array = str_replace("osik","ostik",$array,$i);
$array = str_replace("usz","ucz",$array,$i);
$array = str_replace("kopp","kopf",$array,$i);
$array = str_replace("der","dr",$array,$i);
$array = str_replace("th","t",$array,$i);
$array = str_replace("rh","rg",$array,$i);
$array = str_replace("jce","itse",$array,$i);
$array = str_replace("jts","its",$array,$i);
$array = str_replace("ts","c",$array,$i);

$array = str_replace("myna","mlyna",$array,$i);
$array = str_replace("cova","ckova",$array,$i);
$array = str_replace("0","ne",$array,$i);

$array = str_replace("sevcik","sefcik",$array,$i);
$array = str_replace("scou","scov",$array,$i);
$array = str_replace("adsky","acky",$array,$i);
$array = str_replace("jer","ier",$array,$i);
$array = str_replace("oura","ovra",$array,$i);
$array = str_replace("valchuk","valcuk",$array,$i);
$array = str_replace("ekal","eikal",$array,$i);
$array = str_replace("gei","guei",$array,$i);
$array = str_replace("tai","taj",$array,$i);
$array = str_replace("van","uan",$array,$i);
      
$array = str_replace("2","e",$array,$i);
$array = str_replace("3","s",$array,$i);
$array = str_replace("4","c",$array,$i);
$array = str_replace("5","r",$array,$i);
$array = str_replace("6","z",$array,$i);
$array = str_replace("7","y",$array,$i);
$array = str_replace("8","a",$array,$i);
$array = str_replace("9","i",$array,$i);
$array = str_replace("0","e",$array,$i);
$array = str_replace("/","u",$array,$i);

/* condition start of token */
$array = str_replace("schl","sl",$array,$i);
$array = str_replace("hov","hof",$array,$i);

/* condition: end of token */
$array = str_replace("cko","ko",$array,$i);
$array = str_replace("oukso","osko",$array,$i);
$array = str_replace("ousek","osek",$array,$i);
$array = str_replace("nkova","nova",$array,$i);
$array = str_replace("zkov","zov",$array,$i);

/* condition: middle of token*/
$array = str_replace("rg","rh",$array,$i);
$array = str_replace("erto","ero",$array,$i);
$array = str_replace("stsk","stk",$array,$i);
$array = str_replace("stro","sro",$array,$i);
$array = str_replace("osko","oso",$array,$i);
$array = str_replace("iegle","igle",$array,$i);

$array = str_replace("cti","sti",$array,$i);

$array = str_replace("nkl","nl",$array,$i);
$array = str_replace("end","ed",$array,$i);
 /*     
     "RH","RG"),"ERTO","ERO"),"HOF","HOV")
					,"KO","CKO"),"OUSKO","OUSO"),"OZO","ORO"),"INCO","INO"),"LOVA","OVA")
					,"SCHL","SL"),"CI","CZ"),"BRUCK","BRUCK"),"STI","CTI"),"ZKOV","ZOV")
					,"STRO","SRO"),"STOVA","SOVA"),"NKL","NK"),"END","ED"),"CH","C")
					,"CINSKY","CNICKY"),"STSK","STK"),"RACO","RASO"),"UER","ER")
					
*/					
     
?>